### ISSUE TITLE
why don't use horizon zero:dawn's compose algorithm?

### ISSUE THREAD

**Issue by chena1982** [greje656/clouds#1]
hi, thanks for your share.
in the gpu pro 7 article, Andrew Schneider give the cloud density compose algorithm.
i test it myself, but the result is not good.
i found other implemention on the internet, the result is good. and the author also didn't use the gpu pro 7 compose algorithm.
so, the reason don't use the gpu pro7  compose algorithm is what?
thanks.

http://www.gamedev.net/topic/680832-horizonzero-dawn-cloud-system/

**Comment by greje656** [comment]
aye aye aye :( I forgot that this was developped for stingray 1.5 (not out yet). Im on vacation right now but will fix this when I get back. Thanks for pointing it out!

**Comment by greje656** [comment]
I have'nt seen the gpu pro article yet. im gonna have a look. I just went with the siggraph slides
