### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by chena1982** [greje656/clouds#2]
i put cloud-master in the folder D:\Program Files (x86)\Autodesk\Stingray\1.4.728.0\core\stingray_renderer

and set the renderer in project settings.ini
render_config = "core/stingray_renderer/clouds-master/clouds-resources/renderer"

but the shader compile failed.

Data / Compiler: Start compiling `c5ccf465-f396-4954-830b-a7ac8fe2f002`
Data / Compiler: Error compiling `clouds-resources/clouds.entity`

File not found: `core/components/script.component`
Data / ShaderCompiler: Compiling shader: `generate_clouds:TEXTURE3` ...
Data / Compiler: Error compiling core/stingray_renderer/clouds-master/clouds-resources/clouds.entity

File not found: `core/components/script.component`
Data / Compiler: Compiled core/stingray_renderer/clouds-master/clouds-resources/renderer.render_config
Data / ShaderCompiler: Compiling shader: `generate_godrays` ...
Data / ShaderCompiler: Compiling shader: `generate_clouds:TEXTURE1` ...
Data / ShaderCompiler: Compiling shader: `generate_weather_data:RANDOM` ...
Data / ShaderCompiler: Compiling shader: `raymarch_clouds:SAMPLE_WEATHER_DATA` ...
Data / ShaderCompiler: Compiling shader: `generate_atmosphere` ...
Data / ShaderCompiler: Compiling shader: `merge_clouds_with_scene` ...
Data / ShaderCompiler: Compiling shader: `raymarch_clouds` ...
Data / ShaderCompiler: Compiling shader: `reproject_clouds` ...
Data / ShaderCompiler: Compiling shader: `generate_clouds:TEXTURE2` ...
Data / ShaderCompiler: Compiling shader: `debug_clouds` ...
Data / ShaderCompiler: Compiling shader: `debug_weather` ...
Data / ShaderCompiler: Compiling shader: `generate_weather_data:SCRIPTED` ...
Data / Compiler: Error compiling `clouds-resources/clouds.shader_source`

Failed compiling shader library: (1782): 

Entry point: vs_main
Instruction set: vs_4_0
Error Message:
clouds-resources/clouds.shader_source(1783,19-87): error X3004: undeclared identifier 'safe_range_tone_map_range'
Data / Compiler: Compiling took 7.157125 seconds
Data / RemoteCache: Connected: false, Hits: 0, Misses: 0, RX: 0K, TX 0K
Data / Compiler: Finished compiling `c5ccf465-f396-4954-830b-a7ac8fe2f002`
Editor Engine / ResourcePackage: Failed loading shader_library_group named `clouds-resources/clouds`
Editor Engine / ResourcePackage: Failed loading shader_library named `merge_clouds_with_scene`
Editor Engine: Could not find the shader_library_group named `clouds-resources/clouds`

Assertion failed `_resource_manager.can_get(shader_library_group, name)` at `D:\BuildAgent\work\77aa4c8074a56d3f\git\runtime\application\rendering\shader_library.cpp:177`

Build identifier: `9eb7106118bddd9554fec541c319f8884fceb848`

Product version: `Release (1.4.728.0)`

Thread name: `main`

Error context
----------------------------------------

    ShaderLibraryLoader::take_lib_online clouds-resources/clouds

Callstack
----------------------------------------

    0x40642bba d:\buildagent\work\77aa4c8074a56d3f\git\runtime\foundation\error\error.cpp(265): `anonymous namespace'::report_crash_internal
    0x40642738 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\foundation\error\error.cpp(413): stingray::report_assert_failure
    0x4020d625 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\application\rendering\shader_library.cpp(178): stingray::ShaderLibraryLoader::take_group_online
    0x4020cfa9 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\application\rendering\shader_library.cpp(153): stingray::ShaderLibraryLoader::load_group
    0x4011e5e2 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\application\rendering\render_interface.cpp(666): stingray::RenderInterface::setup
    0x4017bc65 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\application\application.cpp(3218): stingray::Application::config_renderer_setup
    0x406cc2f3 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\foundation\resource\patched_resource_package.cpp(91): stingray::PatchedResourcePackage::flush
    0x4017bad1 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\application\application.cpp(1106): stingray::Application::config_renderer
    0x4017d765 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\application\application.cpp(2396): stingray::Application::init
    0x4018376e d:\buildagent\work\77aa4c8074a56d3f\git\runtime\application\application.cpp(2837): stingray::Application::run
    0x4001d070 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\main\common\actions.cpp(218): stingray::run_application
    0x40001590 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\main\windows\main.cpp(53): run
    0x40001609 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\main\windows\main.cpp(71): safe_run
    0x400017e2 d:\buildagent\work\77aa4c8074a56d3f\git\runtime\main\windows\main.cpp(103): WinMain
    0x40b7fca8 f:\dd\vctools\crt_bld\self_64_amd64\crt\src\crt0.c(238): __tmainCRTStartup
    0x776059bd BaseThreadInitThunk
    0x7783a2e1 RtlUserThreadStart

**Comment by greje656** [comment]
woops. commented on the wrong thread. yes will fix when I get back from holiday. Thanks for pointing it out :)

**Comment by chena1982** [comment]
use render_config_extensions now, but 1.47 still don't work.

**Comment by greje656** [comment]
Hang on tight, Stingray 1.5 is coming soon. Sorry for the inconvenience!

**Comment by chena1982** [comment]
can you give a roug time of 1.5 release?
one week, half month, one moth, or three month?
thanks.

**Comment by greje656** [comment]
Hey Chena, the beta should be already out. The release I think is aimed at early September.

**Comment by chena1982** [comment]
i don't know how to get a beta 1.5, http://www.autodesk.com/education/free-software/stingray, just get version 1.47.
has any method to around this problem?let 1.47 can use this plugin.
thanks.

**Comment by greje656** [comment]
Closing for now. Please re-open if you have problems with 1.5. Thanks!

**Comment by chena1982** [comment]
Hi, i update Stingray to 1.5.863.0, still have compile error.
check this issue: https://github.com/greje656/clouds/issues/9
i use *OzgurCerlet <https://github.com/OzgurCerlet>*'s clouds.shader_source
file
*.*
below is the error log.
can you resolve this?
thanks.


Editor / General: Running Stingray Release at version 1.5.863.0
[e495219095fecbae17e78ddb6e6e32c71b365adb]
Editor / Project Manager: Failed to connect to the Example Registry. Please
try again later.
Data / Compiler: Start compiling `b07ccae6`
*Editor / Stingray Editor: Script action does not have a script defined.*
Data / Compiler: Compiled settings.ini


*Data / Compiler: Error compiling clouds-resources/clouds.entityNo
component compiler for type: ``*
Data / ShaderCompiler: Compiling shader: `merge_clouds_with_scene` ...
Data / ShaderCompiler: Compiling shader: `generate_weather_data:RANDOM` ...
Data / Compiler: Compiled core/stingray_renderer/renderer.render_config
Data / ShaderCompiler: Compiling shader: `reproject_clouds` ...
Data / ShaderCompiler: Compiling shader: `generate_godrays` ...
Data / ShaderCompiler: Compiling shader: `generate_clouds:TEXTURE2` ...
Data / ShaderCompiler: Compiling shader: `generate_clouds:TEXTURE1` ...
Data / ShaderCompiler: Compiling shader: `generate_weather_data:SCRIPTED`
...
Data / ShaderCompiler: Compiling shader: `generate_clouds:TEXTURE3` ...
Data / ShaderCompiler: Compiling shader: `raymarch_clouds` ...
Data / ShaderCompiler: Compiling shader:
`raymarch_clouds:SAMPLE_WEATHER_DATA` ...
Data / ShaderCompiler: Compiling shader: `generate_atmosphere` ...
Data / ShaderCompiler: Compiling shader: `debug_clouds` ...
Data / ShaderCompiler: Compiling shader: `debug_clouds:TILES` ...
Data / ShaderCompiler: Compiling shader: `debug_weather` ...
Data / Compiler: Compiled `clouds-resources/clouds.shader_library_group`
Data / Compiler: Finished compiling `b07ccae6` in 2.4 seconds
Editor Engine / Save: Missing save_dir in settings.ini, disabling save
system.
Editor Engine / Lua: HumanIK initialization script call
Data / Compiler: Start compiling `af3db15d`
Data / Compiler: Error compiling clouds-resources/clouds.entity

No component compiler for type: ``
Error compiling clouds-resources/clouds.entity

No component compiler for type: ``
Data / Compiler: Finished compiling `af3db15d` in 0.042 seconds
